# Generated by Django 5.0.4 on 2024-04-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsuccessfulmodel',
            old_name='bookingSuccessful_city',
            new_name='bookingSuccessful_account_number',
        ),
        migrations.RenameField(
            model_name='bookingsuccessfulmodel',
            old_name='bookingSuccessful_country',
            new_name='bookingSuccessful_order_invoice',
        ),
        migrations.RenameField(
            model_name='bookingsuccessfulmodel',
            old_name='bookingSuccessful_phoneno',
            new_name='bookingSuccessful_payment_mode',
        ),
        migrations.RenameField(
            model_name='bookingsuccessfulmodel',
            old_name='bookingSuccessful_price',
            new_name='bookingSuccessful_total_amount',
        ),
    ]
