# Generated by Django 5.0.4 on 2024-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_paymentApp', '0002_rename_bookingsuccessful_city_bookingsuccessfulmodel_bookingsuccessful_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsuccessfulmodel',
            name='bookingSuccessful_phoneno',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
