# Generated by Django 5.0.4 on 2024-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_paymentApp', '0003_bookingsuccessfulmodel_bookingsuccessful_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='Billing_id',
            field=models.CharField(default=None, max_length=60, primary_key=True, serialize=False),
        ),
    ]
