# Generated by Django 4.2.4 on 2024-05-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_pushnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='PushNotification_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pushnotification',
            old_name='PushNotification_message',
            new_name='message',
        ),
    ]
