# Generated by Django 4.2.4 on 2024-05-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0004_notesmodel_foldernamemodel_foderfilenamemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foldernamemodel',
            old_name='notesname',
            new_name='foldername',
        ),
        migrations.CreateModel(
            name='SchedularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=255)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('color', models.CharField(max_length=255)),
                ('remindertime', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
