# Generated by Django 4.2.4 on 2024-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_rename_notesname_foldernamemodel_foldername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
