# Generated by Django 4.2.4 on 2024-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_examdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularmodel',
            name='isExam',
            field=models.BooleanField(default=False),
        ),
    ]
