# Generated by Django 4.2.4 on 2024-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_schedularmodel_isexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularmodel',
            name='isschedular',
            field=models.BooleanField(default=False),
        ),
    ]
