# Generated by Django 4.2.4 on 2024-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_schedularmodel_isschedular'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularmodel',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
