# Generated by Django 4.2.5 on 2023-12-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bangalowModel',
            fields=[
                ('bangalow_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('bangalow_no', models.TextField(blank=True, default='None', null=True)),
                ('bangalow_bHK', models.TextField(blank=True, default='None', null=True)),
                ('bangalow_area', models.TextField(blank=True, default='None', null=True)),
                ('bangalow_price', models.TextField(blank=True, default='None', null=True)),
                ('bangalow_is_active', models.CharField(default='None')),
                ('bangalow_created_at', models.DateTimeField(auto_now_add=True)),
                ('bangalow_created_at_update', models.CharField(blank=True, default='None', max_length=100, null=True)),
            ],
            options={
                'db_table': 'bangalowmodel_tb',
            },
        ),
        migrations.CreateModel(
            name='clientModel',
            fields=[
                ('client_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('client_bangalow_no', models.TextField(blank=True, default='None', null=True)),
                ('client_first_name', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_last_name', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_email_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_aadhar_card_no', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_pan_card_no', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_proof', models.TextField(blank=True, default='None', null=True)),
                ('client_total_price', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_amount_mode', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_transition', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_transition_payment', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_total_remaining_amount', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_time_period', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_monthly_amount', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client_date', models.DateField(blank=True, default='None', null=True)),
                ('client_is_active', models.CharField(default='None')),
                ('client_created_at', models.DateTimeField(auto_now_add=True)),
                ('client_created_at_update', models.CharField(blank=True, default='None', max_length=100, null=True)),
            ],
            options={
                'db_table': 'clientmodel_tb',
            },
        ),
        migrations.CreateModel(
            name='visitorModel',
            fields=[
                ('visitor_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('visitor_first_name', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('visitor_last_name', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('visitor_location', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('visitor_email_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('visitor_whatapp_phoneNo', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('visitor_phoneNo', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('visitor_is_active', models.CharField(default='None')),
                ('visitor_created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_created_at_update', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('bangalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.bangalowmodel')),
            ],
            options={
                'db_table': 'visitormodel_tb',
            },
        ),
        migrations.CreateModel(
            name='moneyManagementModel',
            fields=[
                ('moneyManagement_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('moneyManagement_amount_mode', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('moneyManagement_amount_payment', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_amount_transition', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_total_remaining_amount', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_remaining_loan_amount', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('moneyManagement_remaining_cash_amount', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('moneyManagement_date', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_transition_proof', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_cheque_photo', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_bank_name', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_bank_branch', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_IFSE_No', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_cheque_No', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_cheque_Ac_No', models.TextField(blank=True, default='None', null=True)),
                ('moneyManagement_is_active', models.CharField(default='None')),
                ('moneyManagement_created_at', models.DateTimeField(auto_now_add=True)),
                ('moneyManagement_created_at_update', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.clientmodel')),
            ],
            options={
                'db_table': 'moneymanagementmodel_tb',
            },
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.visitormodel'),
        ),
    ]
