# Generated by Django 4.2.5 on 2023-12-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_client_transition_payment_clientmodel_client_token_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneymanagementmodel',
            old_name='moneyManagement_amount_payment',
            new_name='moneyManagement_Account_No',
        ),
        migrations.RenameField(
            model_name='moneymanagementmodel',
            old_name='moneyManagement_cheque_Ac_No',
            new_name='moneyManagement_bangalow_no',
        ),
        migrations.RenameField(
            model_name='moneymanagementmodel',
            old_name='moneyManagement_remaining_cash_amount',
            new_name='moneyManagement_phone_no',
        ),
        migrations.RenameField(
            model_name='moneymanagementmodel',
            old_name='moneyManagement_remaining_loan_amount',
            new_name='moneyManagement_remaining_Payment',
        ),
        migrations.AddField(
            model_name='moneymanagementmodel',
            name='moneyManagement_installment_amount',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='moneymanagementmodel',
            name='moneyManagement_token_amount',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='moneymanagementmodel',
            name='moneyManagement_total_amount',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moneymanagementmodel',
            name='moneyManagement_transition',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_date',
            field=models.DateField(blank=True, default='None', null=True),
        ),
    ]
