# Generated by Django 4.2.5 on 2023-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_rename_moneymanagement_amount_payment_moneymanagementmodel_moneymanagement_account_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneymanagementmodel',
            name='moneyManagement_amount_transition',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='client_phone_no',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
