# Generated by Django 4.2.5 on 2023-12-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_moneymanagementmodel_moneymanagement_amount_transition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='client_date',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_date',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
