# Generated by Django 4.2.7 on 2024-01-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_clientmodel_client_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangalowmodel',
            name='bangalow_area',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bangalowmodel',
            name='bangalow_bHK',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bangalowmodel',
            name='bangalow_id',
            field=models.CharField(default='None', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bangalowmodel',
            name='bangalow_no',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bangalowmodel',
            name='bangalow_price',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='client_bangalow_no',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='client_date',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='client_id',
            field=models.CharField(default='None', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='visitor',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.visitormodel'),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='client',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.clientmodel'),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_Account_No',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_IFSE_No',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_bank_branch',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_bank_name',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_cheque_No',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_date',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_id',
            field=models.CharField(default='None', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_installment_amount',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_token_amount',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneymanagementmodel',
            name='moneyManagement_total_remaining_amount',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitormodel',
            name='bangalow',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.bangalowmodel'),
        ),
        migrations.AlterField(
            model_name='visitormodel',
            name='visitor_id',
            field=models.CharField(default='None', max_length=60, primary_key=True, serialize=False),
        ),
    ]
