# Generated by Django 4.2.7 on 2024-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_bangalowmodel_bangalow_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('resume_id', models.CharField(default='None', max_length=60, primary_key=True, serialize=False)),
                ('resume_full_name', models.TextField(blank=True, default='None', null=True)),
                ('resume_phone_no', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_email', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_headline', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_address', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_city', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_education', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_school', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_date', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_description', models.TextField(blank=True, default='None', null=True)),
                ('resume_image', models.ImageField(upload_to='resumes/')),
                ('resume_project_image', models.ImageField(upload_to='resumes/')),
                ('resume_technical_skills', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_soft_skills', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_language', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_hobby', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('resume_is_active', models.CharField(default='None')),
                ('resume_created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_created_at_update', models.CharField(blank=True, default='None', max_length=100, null=True)),
            ],
            options={
                'db_table': 'resumemodel_tb',
            },
        ),
    ]
