# Generated by Django 4.2.7 on 2024-01-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_resumemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='resume_image',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='resume_project_image',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
