# Generated by Django 4.2.4 on 2024-05-04 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('Breathing', 'Breathing'), ('Meditation', 'Meditation'), ('Relaxation', 'Relaxation')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Psychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('short_address', models.CharField(max_length=255)),
                ('full_address', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('number_of_ratings', models.IntegerField()),
                ('image', models.ImageField(upload_to='psych/')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Calm', 'Calm'), ('Happy', 'Happy'), ('Excited', 'Excited'), ('Grateful', 'Grateful'), ('Angry', 'Angry'), ('Sad', 'Sad'), ('Confused', 'Confused'), ('Tired', 'Tired'), ('Neutral', 'Neutral')], default='Neutral', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('image', models.ImageField(upload_to='psych/')),
                ('content_type', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Article', 'Article')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('Breathing', 'Breathing'), ('Meditation', 'Meditation'), ('Relaxation', 'Relaxation')], max_length=20)),
                ('content_type', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Article', 'Article')], max_length=20)),
                ('image', models.ImageField(upload_to='psych/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('mood', models.CharField(choices=[('Calm', 'Calm'), ('Happy', 'Happy'), ('Excited', 'Excited'), ('Grateful', 'Grateful'), ('Angry', 'Angry'), ('Sad', 'Sad'), ('Confused', 'Confused'), ('Tired', 'Tired'), ('Neutral', 'Neutral')], default='Neutral', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_views', models.IntegerField(default=0)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('segments', models.ManyToManyField(blank=True, to='core.sessionpart')),
            ],
        ),
        migrations.CreateModel(
            name='RecentSessionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.ManyToManyField(to='core.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteSessionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_segments', models.ManyToManyField(to='core.sessionpart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.ManyToManyField(to='core.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePsychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychiatrists', models.ManyToManyField(to='core.psychiatrist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedSessionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
