# Generated by Django 5.0.4 on 2024-05-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientdetailModel',
            fields=[
                ('patientdetail_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('patientdetail_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientdetail_doctor_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientdetail_diseases_description', models.TextField(blank=True, default=None, null=True)),
                ('patientdetail_mobile_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientdetail_totalprice', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientdetail_is_active', models.BooleanField(default=True)),
                ('patientdetail_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patientdetailmodel_tb',
            },
        ),
        migrations.CreateModel(
            name='patientmedicineModel',
            fields=[
                ('patientmedicine_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('patientmedicine_medicine_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientmedicine_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientmedicine_quantity', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientmedicine_remember_quantity', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientmedicine_totalprice', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patientmedicine_is_active', models.BooleanField(default=True)),
                ('patientmedicine_created_at', models.DateTimeField(auto_now_add=True)),
                ('patientmedicine_created_at_update', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('medicine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminpanelApp.medicinemodel')),
                ('patientdetail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminpanelApp.patientdetailmodel')),
            ],
            options={
                'db_table': 'patientmedicinemodel_tb',
            },
        ),
        migrations.DeleteModel(
            name='patienthistoryModel',
        ),
    ]
