# Generated by Django 5.0.4 on 2024-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0002_patientdetailmodel_patientmedicinemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicinemodel',
            name='patientdetail',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
