# Generated by Django 5.0.4 on 2024-05-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0003_alter_patientmedicinemodel_patientdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicinemodel',
            name='patientdetail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminpanelApp.patientdetailmodel'),
        ),
    ]
