# Generated by Django 5.0.4 on 2024-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0004_alter_patientmedicinemodel_patientdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicinemodel',
            name='patientmedicine_mg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
