# Generated by Django 5.0.4 on 2024-05-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0006_medicinemodel_medicine_remember_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_expiry_date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_mfg_date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
