# Generated by Django 5.0.4 on 2024-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0007_alter_medicinemodel_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('user_id', models.CharField(default='None', max_length=60, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('user_lname', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('user_gender', models.CharField(blank=True, default='None', max_length=10, null=True)),
                ('user_mobile_num', models.CharField(blank=True, default='None', max_length=15, null=True)),
                ('user_username', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('user_password', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('user_emp_type', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('user_is_active', models.CharField(default='None')),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created_at_update', models.CharField(blank=True, default='None', max_length=100, null=True)),
            ],
            options={
                'db_table': 'adminuser_tb',
            },
        ),
    ]
