# Generated by Django 5.0.4 on 2024-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0008_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='medicine_barcode',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
