# Generated by Django 5.0.4 on 2024-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0009_medicinemodel_medicine_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_barcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='barcodes/'),
        ),
    ]
