# Generated by Django 5.0.3 on 2024-03-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('user_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user_lname', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user_mobile_num', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('user_username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_password', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created_at_update', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
        migrations.CreateModel(
            name='customizeModel',
            fields=[
                ('customize_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('customize_image', models.TextField(blank=True, default=None, null=True)),
                ('customize_video_path', models.TextField(blank=True, default=None, null=True)),
                ('customize_video_download_link', models.TextField(blank=True, default=None, null=True)),
                ('customize_created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductAR.usermodel')),
            ],
            options={
                'db_table': 'customizemodel_tb',
            },
        ),
    ]
