# Generated by Django 5.0.3 on 2024-03-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductAR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customizeModel',
        ),
    ]
