# Generated by Django 5.0.3 on 2024-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductAR', '0003_customizemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizemodel',
            name='customize_video_AmbientLight',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizemodel',
            name='customize_video_Dimension',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizemodel',
            name='customize_video_DirectionalLight',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizemodel',
            name='customize_video_PointLight',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizemodel',
            name='customize_video_SpotLight',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
