# Generated by Django 5.0.3 on 2024-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductAR', '0004_customizemodel_customize_video_ambientlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
