# Generated by Django 5.0.3 on 2024-04-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductAR', '0005_alter_usermodel_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
