# Generated by Django 5.0.4 on 2024-04-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flightApp', '0001_initial'),
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflightbookmodel',
            name='userGuest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.userguestmodel'),
        ),
    ]
