# Generated by Django 5.0.4 on 2024-04-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflightbookmodel',
            name='user',
        ),
    ]
