# Generated by Django 5.0.4 on 2024-04-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_remove_userflightbookmodel_user'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflightbookmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApp.signupmodel'),
        ),
    ]
