# Generated by Django 5.0.4 on 2024-04-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0004_userflightbookmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightclassmodel',
            old_name='flight',
            new_name='flightDetails',
        ),
        migrations.RenameField(
            model_name='flightfacilitiesmodel',
            old_name='flight',
            new_name='flightDetails',
        ),
        migrations.RenameField(
            model_name='flightmodel',
            old_name='flightstay_icon',
            new_name='flight_icon',
        ),
        migrations.RemoveField(
            model_name='flightdetailsmodel',
            name='flightClass',
        ),
        migrations.RemoveField(
            model_name='flightdetailsmodel',
            name='flightFacilities',
        ),
    ]
