# Generated by Django 5.0.4 on 2024-04-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0005_rename_flight_flightclassmodel_flightdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightclassmodel',
            name='flightDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='flightfacilitiesmodel',
            name='flightDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='userflightbookmodel',
            name='flightDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightdetailsmodel'),
        ),
    ]
