# Generated by Django 5.0.4 on 2024-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmodel',
            name='Destinationstay_image',
            field=models.ImageField(default=1, upload_to='destination/'),
            preserve_default=False,
        ),
    ]
