# Generated by Django 5.0.6 on 2024-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('user_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user_lname', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user_mobile_num', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('user_username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_password', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created_at_update', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
    ]
