# Generated by Django 5.0.6 on 2024-05-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistModel',
            fields=[
                ('wishlist_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('wishlist_user', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('wishlist_product', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
    ]
