# Generated by Django 5.0.4 on 2024-04-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguestmodel',
            name='userGuest_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
