# Generated by Django 5.0.4 on 2024-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_alter_userguestmodel_userguest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguestmodel',
            name='userGuest_id',
            field=models.CharField(default=None, max_length=60, primary_key=True, serialize=False),
        ),
    ]
